Fix keycode custom control
the-via/app pull request #103
Opened 2023-01-19 04:48 UTC by wilba

Custom menu keycode control is only loading/saving one byte, should be two bytes.

2023-01-20 06:33 UTC, olivia requested changes

2023-01-20 06:33 UTC, olivia commented on src/components/panes/configure-panes/custom/custom-control.tsx
> +const shiftFrom16Bit = (value: number): [number, number] => [
Those two functions already exist in keyboard-api

2023-01-21 01:13 UTC, wilba commented
I will fix range control as well, don't merge yet

2023-01-24 17:42 UTC, olivia requested changes

2023-01-24 17:42 UTC, olivia commented on src/components/panes/configure-panes/custom/custom-control.tsx
> +  debugger;
You should remove debugger statements

2023-01-24 20:05 UTC, wilba commented on src/components/panes/configure-panes/custom/custom-control.tsx
> +  debugger;
fixed

2023-01-25 05:33 UTC, olivia approved these changes

2023-01-25 05:33 UTC, merged