Main to fiber
the-via/app pull request #111
Opened 2023-02-03 12:46 UTC by ValdisThomann

2023-02-03 12:57 UTC, wilba requested changes

2023-02-03 12:57 UTC, wilba commented on src/utils/keyboard-rendering.ts
> +    const userKeycodeIdx = getCustomKeycodeIndex(keycodeByte, basicKeyToByte);
change userKeycodeIdx to customKeycodeIdx

2023-02-03 12:57 UTC, wilba commented on src/utils/key.ts
> +export function mapEvtToKeycode(evt: KeyboardEvent) {
Was this function deleted in fiber branch and being added back in from main?

2023-02-03 13:05 UTC, ValdisThomann commented on src/utils/keyboard-rendering.ts
> +    const userKeycodeIdx = getCustomKeycodeIndex(keycodeByte, basicKeyToByte);
done

2023-02-03 13:06 UTC, ValdisThomann commented on src/utils/advanced-keys.ts
> +  debugger;
done

2023-02-03 13:19 UTC, wilba commented on src/utils/key.ts
> +        {name: '/', code: 'KC_PSLS', keys: 'num_divide', title: 'Numpad /'},
keep ÷ and ×

2023-02-03 13:22 UTC, ValdisThomann commented on src/utils/key.ts
> +        {name: '/', code: 'KC_PSLS', keys: 'num_divide', title: 'Numpad /'},
Ok. This was auto-merged though, which means they were removed in fiber for some reason.

2023-02-03 13:26 UTC, ValdisThomann commented on src/utils/key.ts
> +        {name: '/', code: 'KC_PSLS', keys: 'num_divide', title: 'Numpad /'},
Just confirming: you want ÷ and × instead of / and * ? Isn't the latter standard on a numpad?

2023-02-04 02:34 UTC, wilba commented on src/utils/key.ts
> +        {name: '/', code: 'KC_PSLS', keys: 'num_divide', title: 'Numpad /'},
yes

2023-02-04 02:35 UTC, ValdisThomann commented on src/utils/key.ts
> +        {name: '/', code: 'KC_PSLS', keys: 'num_divide', title: 'Numpad /'},
done

2023-02-04 02:36 UTC, merged