Add RGB Hexadecimal text input to colour picker
the-via/app pull request #170
Opened 2023-06-14 10:20 UTC by miccou

![image](https://github.com/the-via/app/assets/30512204/6c912dcf-bd49-456f-a1a6-91a6e2cec01d)

- Adds a text input above the colour picker.
- If you drag the mouse to pick a colour, the hex code updates.
- Hex code inputs is restricted to base16 chars.
- Pressing enter after typing or pasting a hex colour code chooses the same colour by hue and sat but with 100% luminance.
- Pressing enter without a valid 3 or 6 character hex colour code will do nothing
- Clicking out of the colour picker will reset the text box to match the selected colour

2023-06-21 23:14 UTC, miccou commented
@olivia would yourself or another maintainer have time to consider this PR?

2023-06-25 19:19 UTC, olivia requested changes
Thank you very much for the contribution ❤️ I have some code changes requested and could you also update the positioning of the tooltip tail (the triangle)? Right now it doesn't point at the control in the screenshot you posted.

2023-06-25 19:19 UTC, olivia commented on src/components/inputs/color-picker.tsx
> +  hsToRgb({hue, sat}: {hue: number; sat: number}) {
Can you move this and the next function into `app/src/utils/color-math.ts`? There already is a a `getRGB` function and it would be good to update that to call `hsToRGB`

2023-06-27 08:38 UTC, miccou commented on src/components/inputs/color-picker.tsx
> +  hsToRgb({hue, sat}: {hue: number; sat: number}) {
I've moved the colour space conversion to `app/src/utils/color-math.ts`

2023-06-27 08:38 UTC, miccou commented
Thanks for your feedback @olivia, I've address these with commits to my feature branch.

2023-06-28 16:42 UTC, olivia approved these changes
Looks good, thank you for making the requested edits!

2023-06-28 16:43 UTC, merged